Laxmi1975 patch 1
GSA/idmanagement.gov pull request #1212
Opened 2024-11-21 16:22 UTC by laxmi1975

Unifyia Implementation Guide

2024-11-21 16:30 UTC, laxmi1975 commented
Please review my PR.

2024-11-21 22:26 UTC, id2win requested changes
Please share the preview page link via email with me, I will start an internal review, once that is complete, we can proceed with the merge. Thanks.

2024-11-22 09:13 UTC, laxmi1975 commented
> Please share the preview page link via email with me, I will start an internal review, once that is complete, we can proceed with the merge. Thanks.

> I have emailed you the link. Thanks.

2024-11-26 16:09 UTC, JBPayne007 approved these changes

2024-11-26 17:19 UTC, merged